### PR TITLE
Change tag value

### PR DESCRIPTION
**Pull request by aoktox**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes https://github.com/traveloka/terraform-aws-autoscaling/issues/44

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-autoscaling/blob/master/CHANGELOG.md):

```release-note
NOTES:

* Change Name tag value

FEATURES:

* 

ENHANCEMENTS:

* 

BUG FIXES:

* Prevent error `diffs didn't match during apply`
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan
...
tags.#:                                     "7"
tags.1141493681.%:                          "3"
tags.1141493681.key:                        "Environment"
tags.1141493681.propagate_at_launch:        "0"
tags.1141493681.value:                      "staging"
tags.1549330624.%:                          "3"
tags.1549330624.key:                        "ManagedBy"
tags.1549330624.propagate_at_launch:        "0"
tags.1549330624.value:                      "terraform"
tags.1627912306.%:                          "3"
tags.1627912306.key:                        "AmiId"
tags.1627912306.propagate_at_launch:        "1"
tags.1627912306.value:                      "ami-02959f2ed559ac605"
tags.2091551781.%:                          "3"
tags.2091551781.key:                        "Service"
tags.2091551781.propagate_at_launch:        "0"
tags.2091551781.value:                      "payepg"
tags.2209837006.%:                          "3"
tags.2209837006.key:                        "ProductDomain"
tags.2209837006.propagate_at_launch:        "0"
tags.2209837006.value:                      "pay"
tags.2625938796.%:                          "3"
tags.2625938796.key:                        "Name"
tags.2625938796.propagate_at_launch:        "0"
tags.2625938796.value:                      "payepg-app"
tags.2664787174.%:                          "3"
tags.2664787174.key:                        "Description"
tags.2664787174.propagate_at_launch:        "0"
tags.2664787174.value:                      "ASG of the payepg-app cluster"
...
```

### CODE REVIEW

**Comment by aoktox** [comment]
cc @salvianreynaldi

**Comment by salvianreynaldi** [comment]
My only concern is that this makes the `Name` tag not accurate, as the actual asg_name has a random suffix
Cost explorer / datadog / other things that do filtering by tags might be impacted

**Comment by salvianreynaldi** [comment]
is it okay to actually change the asg name as well? (removing the random suffix)

**Comment by salvianreynaldi** [comment]
maybe it's good to also have @rafikurnia's input here

**Comment by rafikurnia** [comment]
Can I see the error `diffs didn't match during apply`? I assume you think that the random_id is causing the issue, my question is that why the error occurred and how can the random_id on the tag Name causing the problem?

**Comment by aoktox** [comment]
> My only concern is that this makes the `Name` tag not accurate, as the actual asg_name has a random suffix
> Cost explorer / datadog / other things that do filtering by tags might be impacted

Does Cost explorer / datadog use ASG tag instead of instance tag @salvianreynaldi ?

**Comment by aoktox** [comment]
> Can I see the error `diffs didn't match during apply`? I assume you think that the random_id is causing the issue, my question is that why the error occurred and how can the random_id on the tag Name causing the problem?

I think the `Name` tag not referring to non existing resource (naming module) since when i apply naming module first, i got different plan output. You can see the detail here (https://github.com/traveloka/terraform-aws-autoscaling/issues/44) @rafikurnia

**Comment by salvianreynaldi** [comment]
> > My only concern is that this makes the `Name` tag not accurate, as the actual asg_name has a random suffix
> > Cost explorer / datadog / other things that do filtering by tags might be impacted
> 
> Does Cost explorer / datadog use ASG tag instead of instance tag @salvianreynaldi ?

ah, good question. I'm not sure though
However, instances get their names from the ASG `Name` tag, right? because we don't actually tag each instance 1 by 1

**Comment by aoktox** [comment]
> However, instances get their names from the ASG `Name` tag, right? because we don't actually tag each instance 1 by 1

@salvianreynaldi i think EC2 instances mostly get its tags from launch template
https://github.com/traveloka/terraform-aws-autoscaling/blob/b4939360d89a2a665fe6356e9ba9291ac4b24343/main.tf#L74-L99

**Comment by salvianreynaldi** [comment]
> > However, instances get their names from the ASG `Name` tag, right? because we don't actually tag each instance 1 by 1
> 
> @salvianreynaldi i think EC2 instances mostly get its tags from launch template
> https://github.com/traveloka/terraform-aws-autoscaling/blob/b4939360d89a2a665fe6356e9ba9291ac4b24343/main.tf#L74-L99

you're right, sorry. With launch template, instances tags are retrieved from the launch template itself.

So this looks good. What do you think, @rafikurnia ?

**Pull request merged**
